Nome = input("Digite o seu nome: ")
Idade = input("Digite a sua idade: ")
Email = input("Digite o seu e-mail: ")
Data = input("Digite a sua data de nascimento: ")
Telefone = input("Digite o seu número de telefone: ")

print("\nNome: ", Nome)
print("Idade: ", Idade)
print("E-mail: ", Email)
print("Data: ", Data)
print("Telefone: ", Telefone)